// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Data;

#nullable disable

namespace UserManagement.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240311193838_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Data.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 36, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 37, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 38, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 39, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 40, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 41, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 42, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 43, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 44, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 45, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 10L
                        },
                        new
                        {
                            Id = 11L,
                            Changes = "Changes",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 46, 0, DateTimeKind.Unspecified),
                            Type = "Created User",
                            UserId = 11L
                        },
                        new
                        {
                            Id = 12L,
                            Changes = "Changes for Update",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 36, 0, DateTimeKind.Unspecified),
                            Type = "Updated User",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 13L,
                            Changes = "Changes for Update",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 36, 0, DateTimeKind.Unspecified),
                            Type = "Updated User",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 14L,
                            Changes = "Changes for Deletion",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 36, 0, DateTimeKind.Unspecified),
                            Type = "Deleted User",
                            UserId = 5L
                        },
                        new
                        {
                            Id = 15L,
                            Changes = "Changes for Deletion",
                            CreatedAt = new DateTime(2024, 3, 11, 13, 52, 36, 0, DateTimeKind.Unspecified),
                            Type = "Deleted User",
                            UserId = 6L
                        });
                });

            modelBuilder.Entity("UserManagement.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateOfBirth = "1985-01-15",
                            Email = "ploew@example.com",
                            Forename = "Peter",
                            IsActive = true,
                            Surname = "Loew"
                        },
                        new
                        {
                            Id = 2L,
                            DateOfBirth = "1990-03-27",
                            Email = "bfgates@example.com",
                            Forename = "Benjamin Franklin",
                            IsActive = true,
                            Surname = "Gates"
                        },
                        new
                        {
                            Id = 3L,
                            DateOfBirth = "1976-06-08",
                            Email = "ctroy@example.com",
                            Forename = "Castor",
                            IsActive = false,
                            Surname = "Troy"
                        },
                        new
                        {
                            Id = 4L,
                            DateOfBirth = "2002-09-05",
                            Email = "mraines@example.com",
                            Forename = "Memphis",
                            IsActive = true,
                            Surname = "Raines"
                        },
                        new
                        {
                            Id = 5L,
                            DateOfBirth = "1995-12-20",
                            Email = "sgodspeed@example.com",
                            Forename = "Stanley",
                            IsActive = true,
                            Surname = "Goodspeed"
                        },
                        new
                        {
                            Id = 6L,
                            DateOfBirth = "2005-01-23",
                            Email = "himcdunnough@example.com",
                            Forename = "H.I.",
                            IsActive = true,
                            Surname = "McDunnough"
                        },
                        new
                        {
                            Id = 7L,
                            DateOfBirth = "1998-04-10",
                            Email = "cpoe@example.com",
                            Forename = "Cameron",
                            IsActive = false,
                            Surname = "Poe"
                        },
                        new
                        {
                            Id = 8L,
                            DateOfBirth = "1980-07-03",
                            Email = "emalus@example.com",
                            Forename = "Edward",
                            IsActive = false,
                            Surname = "Malus"
                        },
                        new
                        {
                            Id = 9L,
                            DateOfBirth = "2005-11-18",
                            Email = "dmacready@example.com",
                            Forename = "Damon",
                            IsActive = false,
                            Surname = "Macready"
                        },
                        new
                        {
                            Id = 10L,
                            DateOfBirth = "1972-02-28",
                            Email = "jblaze@example.com",
                            Forename = "Johnny",
                            IsActive = true,
                            Surname = "Blaze"
                        },
                        new
                        {
                            Id = 11L,
                            DateOfBirth = "1993-09-15",
                            Email = "rfeld@example.com",
                            Forename = "Robin",
                            IsActive = true,
                            Surname = "Feld"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
